### ISSUE TITLE
Authentication Required Toast

### ISSUE THREAD

**Issue by louisbaclao** [eljannero/CentralPharmacy#28]
Upon login of user account, the toast for **"Authentication required. Please log in."** keeps on showing the same time with **"Welcome, End user"** toast.

**Expected behavior**
Only the **"Welcome"** toast is expected to show

**Comment by eljannero** [comment]
Fixed. [](https://github.com/eljannero/CentralPharmacy/commit/3d4875e6f1b54c91f851bf81f9f0691880bb685b)

**Comment by eljannero** [comment]
Fixed on commit [https://github.com/eljannero/CentralPharmacy/commit/3d4875e6f1b54c91f851bf81f9f0691880bb685b](url)
